// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/artni96/go-musthave-diploma-tpl/internal/gophermart/service/balances (interfaces: BalanceServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/artni96/go-musthave-diploma-tpl/internal/gophermart/model"
	gomock "github.com/golang/mock/gomock"
)

// MockBalanceServiceInterface is a mock of BalanceServiceInterface interface.
type MockBalanceServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceServiceInterfaceMockRecorder
}

// MockBalanceServiceInterfaceMockRecorder is the mock recorder for MockBalanceServiceInterface.
type MockBalanceServiceInterfaceMockRecorder struct {
	mock *MockBalanceServiceInterface
}

// NewMockBalanceServiceInterface creates a new mock instance.
func NewMockBalanceServiceInterface(ctrl *gomock.Controller) *MockBalanceServiceInterface {
	mock := &MockBalanceServiceInterface{ctrl: ctrl}
	mock.recorder = &MockBalanceServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceServiceInterface) EXPECT() *MockBalanceServiceInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockBalanceServiceInterface) Get(arg0 *context.Context, arg1 string) (model.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(model.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBalanceServiceInterfaceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBalanceServiceInterface)(nil).Get), arg0, arg1)
}

// Withdraw mocks base method.
func (m *MockBalanceServiceInterface) Withdraw(arg0 *context.Context, arg1 model.TransactionCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockBalanceServiceInterfaceMockRecorder) Withdraw(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockBalanceServiceInterface)(nil).Withdraw), arg0, arg1)
}
