// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/artni96/go-musthave-diploma-tpl/internal/gophermart/repository/balances (interfaces: BalanceRepositoryInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/artni96/go-musthave-diploma-tpl/internal/gophermart/model"
	gomock "github.com/golang/mock/gomock"
)

// MockBalanceRepositoryInterface is a mock of BalanceRepositoryInterface interface.
type MockBalanceRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepositoryInterfaceMockRecorder
}

// MockBalanceRepositoryInterfaceMockRecorder is the mock recorder for MockBalanceRepositoryInterface.
type MockBalanceRepositoryInterfaceMockRecorder struct {
	mock *MockBalanceRepositoryInterface
}

// NewMockBalanceRepositoryInterface creates a new mock instance.
func NewMockBalanceRepositoryInterface(ctrl *gomock.Controller) *MockBalanceRepositoryInterface {
	mock := &MockBalanceRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockBalanceRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepositoryInterface) EXPECT() *MockBalanceRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockBalanceRepositoryInterface) Get(arg0 *context.Context, arg1 string) (model.BalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(model.BalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBalanceRepositoryInterfaceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBalanceRepositoryInterface)(nil).Get), arg0, arg1)
}

// Withdraw mocks base method.
func (m *MockBalanceRepositoryInterface) Withdraw(arg0 *context.Context, arg1 model.TransactionCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockBalanceRepositoryInterfaceMockRecorder) Withdraw(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockBalanceRepositoryInterface)(nil).Withdraw), arg0, arg1)
}
